services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ${DATA_ROOT:-./data}/config:/config
      - ${DATA_ROOT:-./data}/cache:/cache
      - ${MEDIA_ROOT:-./media}:/media
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
    networks:
      - frontend

networks:
  frontend:
    external: true