services:
  server:
    image: ghcr.io/goauthentik/server:6.5.3
    container_name: authentik-server
    command: server
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9443:9443
    environment:
      - AUTHENTIK_POSTGRESQL__HOST=${POSTGRESQL_HOST}
      - AUTHENTIK_POSTGRESQL__PORT=${POSTGRESQL_PORT}
      - AUTHENTIK_POSTGRESQL__USER=${POSTGRESQL_USER}
      - AUTHENTIK_POSTGRESQL__NAME=${POSTGRESQL_NAME}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${POSTGRESQL_PASSWORD}
      - AUTHENTIK_SECRET_KEY=${SECRET_KEY}
      - AUTHENTIK_ERROR_REPORTING__ENABLED=true
      - AUTHENTIK_EMAIL__HOST=${EMAIL_HOST}
      - AUTHENTIK_EMAIL__PORT=${EMAIL_PORT}
      - AUTHENTIK_EMAIL__USERNAME=${EMAIL_USERNAME}
      - AUTHENTIK_EMAIL__PASSWORD=${EMAIL_PASSWORD}
      - AUTHENTIK_EMAIL__USE_TLS=${EMAIL_USE_TLS}
      - AUTHENTIK_EMAIL__USE_SSL=${EMAIL_USE_SSL}
      - AUTHENTIK_EMAIL__TIMEOUT=10
      - AUTHENTIK_EMAIL__FROM=${EMAIL_FROM}
    volumes:
      - /home/authentik/media:/media
      - /home/authentik/custom-templates:/templates
    security_opt:
      - no-new-privileges=true
    env_file:
      - .env
    networks:
      - frontend
      - backend

  worker:
    image: ghcr.io/goauthentik/server:2026.5.3
    container_name: authentik-worker
    command: worker
    user: root
    restart: unless-stopped
    environment:
      - AUTHENTIK_POSTGRESQL__HOST=${POSTGRESQL_HOST}
      - AUTHENTIK_POSTGRESQL__PORT=${POSTGRESQL_PORT}
      - AUTHENTIK_POSTGRESQL__USER=${POSTGRESQL_USER}
      - AUTHENTIK_POSTGRESQL__NAME=${POSTGRESQL_NAME}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${POSTGRESQL_PASSWORD}
      - AUTHENTIK_SECRET_KEY=${SECRET_KEY}
      - AUTHENTIK_ERROR_REPORTING__ENABLED=true
      - AUTHENTIK_EMAIL__HOST=${EMAIL_HOST}
      - AUTHENTIK_EMAIL__PORT=${EMAIL_PORT}
      - AUTHENTIK_EMAIL__USERNAME=${EMAIL_USERNAME}
      - AUTHENTIK_EMAIL__PASSWORD=${EMAIL_PASSWORD}
      - AUTHENTIK_EMAIL__USE_TLS=${EMAIL_USE_TLS}
      - AUTHENTIK_EMAIL__USE_SSL=${EMAIL_USE_SSL}
      - AUTHENTIK_EMAIL__TIMEOUT=10
      - AUTHENTIK_EMAIL__FROM=${EMAIL_FROM}
    volumes:
      - /run/docker.sock:/run/docker.sock
      - /home/authentik/media:/media
      - /home/authentik/certs:/certs
      - /home/authentik/custom-templates:/templates
    security_opt:
      - no-new-privileges=true
    env_file:
      - .env
    networks:
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true