services:
  pgadmin:
    image: dpage/pgadmin4:latest@sha256:c332c5f6dfba995d9ebc4af261d93506d6876085d712eaaa3defc8dd1a3f26de
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_AUTHENTICATION_SOURCES=${AUTHENTICATION_SOURCES}
      - PGADMIN_CONFIG_OAUTH2_AUTO_CREATE_USER=${AUTO_CREATE_USER}
      - PGADMIN_CONFIG_OAUTH2_CONFIG=${OAUTH2_CONFIG}
    volumes:
      - ${DATA_ROOT:-./data}:/var/lib/pgadmin
    env_file:
      - .env
    networks:
      - frontend
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true
