services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_AUTHENTICATION_SOURCES=${AUTHENTICATION_SOURCES}
      - PGADMIN_CONFIG_OAUTH2_AUTO_CREATE_USER=${AUTO_CREATE_USER}
      - PGADMIN_CONFIG_OAUTH2_CONFIG=${OAUTH2_CONFIG}
    volumes:
      - /home/pgadmin/data:/var/lib/pgadmin
      - /home/pgadmin/config_local.py:/pgadmin4/config_local.py
    env_file:
      - .env
    networks:
      - frontend
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true