services:
  server:
    image: ghcr.io/goauthentik/server:2025.10.3
    container_name: authentik-server
    command: server
    restart: unless-stopped
    environment:
      - AUTHENTIK_POSTGRESQL__HOST=${POSTGRESQL_HOST}
      - AUTHENTIK_POSTGRESQL__PORT=${POSTGRESQL_PORT}
      - AUTHENTIK_POSTGRESQL__USER=${POSTGRESQL_USER}
      - AUTHENTIK_POSTGRESQL__NAME=${POSTGRESQL_NAME}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${POSTGRESQL_PASSWORD}
      - AUTHENTIK_SECRET_KEY=${SECRET_KEY}
      - AUTHENTIK_ERROR_REPORTING__ENABLED=true
      - AUTHENTIK_EMAIL__HOST=${EMAIL_HOST}
      - AUTHENTIK_EMAIL__PORT=${EMAIL_PORT}
      - AUTHENTIK_EMAIL__USERNAME=${EMAIL_USERNAME}
      - AUTHENTIK_EMAIL__PASSWORD=${EMAIL_PASSWORD}
      - AUTHENTIK_EMAIL__USE_TLS=${EMAIL_USE_TLS}
      - AUTHENTIK_EMAIL__USE_SSL=${EMAIL_USE_SSL}
      - AUTHENTIK_EMAIL__TIMEOUT=10
      - AUTHENTIK_EMAIL__FROM=${EMAIL_FROM}
    ports:
      - 9000:9000
      - 9443:9443
    security_opt:
      - no-new-privileges=true
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    env_file:
      - .env

  worker:
    image: ghcr.io/goauthentik/server:2025.10.3
    container_name: authentik-worker
    command: worker
    restart: unless-stopped
    environment:
      - AUTHENTIK_POSTGRESQL__HOST=${POSTGRESQL_HOST}
      - AUTHENTIK_POSTGRESQL__PORT=${POSTGRESQL_PORT}
      - AUTHENTIK_POSTGRESQL__USER=${POSTGRESQL_USER}
      - AUTHENTIK_POSTGRESQL__NAME=${POSTGRESQL_NAME}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${POSTGRESQL_PASSWORD}
      - AUTHENTIK_SECRET_KEY=${SECRET_KEY}
      - AUTHENTIK_ERROR_REPORTING__ENABLED=true
      - AUTHENTIK_EMAIL__HOST=${EMAIL_HOST}
      - AUTHENTIK_EMAIL__PORT=${EMAIL_PORT}
      - AUTHENTIK_EMAIL__USERNAME=${EMAIL_USERNAME}
      - AUTHENTIK_EMAIL__PASSWORD=${EMAIL_PASSWORD}
      - AUTHENTIK_EMAIL__USE_TLS=${EMAIL_USE_TLS}
      - AUTHENTIK_EMAIL__USE_SSL=${EMAIL_USE_SSL}
      - AUTHENTIK_EMAIL__TIMEOUT=10
      - AUTHENTIK_EMAIL__FROM=${EMAIL_FROM}
    user: root
    volumes:
      - /run/docker.sock:/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    env_file:
      - .env
    networks:
      - proxy
networks:
  proxy:
    external: true