services:
  pve-exporter:
    image: prompve/prometheus-pve-exporter:3.10.0@sha256:4867684c0a937716f11f770a32d32958bded507cf570fc334f774392afcb2f37
    container_name: pve-exporter
    restart: unless-stopped
    ports:
      - "9221:9221"
    volumes:
      - ${PVE_EXPORTER_CONFIG:-./pve.yml}:/etc/prometheus/pve.yml:ro
    security_opt:
      - no-new-privileges=true
    networks:
      - backend

networks:
  backend:
    external: true
