services:
  lancache_dns:
    image: lancachenet/lancache-dns:latest@sha256:cec61382a3b4b8ef6dfc4ff44eefd4028ea48662ff5930097bb366b69e22296c
    container_name: lancache_dns
    restart: unless-stopped
    ports:
      - ${DNS_BIND_IP}:53:53/udp
      - ${DNS_BIND_IP}:53:53/tcp
    security_opt:
      - no-new-privileges=true
    env_file: .env
    networks:
      - backend

  monolithic:
    image: lancachenet/monolithic:latest@sha256:37f28b362c939a333f3e4f12aa8ca80604cf75050b2f190d0ad972b2fedce00e
    container_name: lancache_monolithic
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ${DATA_ROOT:-./data}/cache:/data/cache
      - ${DATA_ROOT:-./data}/logs:/data/logs
    security_opt:
      - no-new-privileges=true
    env_file: .env
    networks:
      - backend

networks:
  backend:
    external: true