services:
  comfyui:
    image: comfyanonymous/comfyui:latest
    container_name: comfyui
    restart: unless-stopped
    ports:
      - 8188:8188
    volumes:
      - ${DATA_ROOT:-./data}:/workspace/ComfyUI:rw
      - ${DATA_ROOT:-./data}/output:/workspace/ComfyUI/output:rw
      - ${DATA_ROOT:-./data}/input:/workspace/ComfyUI/input:rw
#      
      - ${DATA_ROOT:-./data}/models:/workspace/ComfyUI/models
#      
      - ${DATA_ROOT:-./data}/config:/workspace/ComfyUI/config:rw
      - ${DATA_ROOT:-./data}/custom_nodes:/workspace/ComfyUI/custom_nodes:rw
    ulimits:
      memlock: -1
    mem_limit: 16gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - frontend

networks:
  frontend:
    external: true