services:
  comfyui:
    image: comfyanonymous/comfyui:latest
    container_name: comfyui
    restart: unless-stopped
    ports:
      - 8188:8188
    volumes:
      - /home/comfy-data:/workspace/ComfyUI:rw
      - /mnt/comfyui/output:/workspace/ComfyUI/output:rw
      - /mnt/comfyui/input:/workspace/ComfyUI/input:rw
#      
      - /mnt/comfyui/models:/workspace/ComfyUI/models
#      
      - /home/comfyui/config:/workspace/ComfyUI/config:rw
      - /home/comfyui/custom_nodes:/workspace/ComfyUI/custom_nodes:rw
    ulimits:
      memlock: -1
    mem_limit: 16gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - frontend

networks:
  frontend:
    external: true