services:
  seerr:
    container_name: seerr
    image: ghcr.io/hotio/seerr:latest
    restart: unless-stopped
    ports:
      - 5055:5055
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UNMASK=002
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/seerr:/config
      - /mnt/media:/data
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
    networks:
      - frontend
      - backend

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UNMASK=002
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/prowlarr:/config
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
    networks:
      - backend

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UNMASK=002
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/radarr:/config
      - /mnt/media:/data
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
    networks:
      - backend

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    ports:
     - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UNMASK=002
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/sonarr:/config
      - /mnt/media:/data
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
    networks:
      - backend

  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr:latest
    restart: unless-stopped
    ports:
      - 8686:8686
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UNMASK=002
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/lidarr:/config
      - /mnt/media:/data
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
    networks:
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true