---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.2
    container_name: homepage
    ports:
      - 3000:3000
    environment:
      - PUID=1026
      - PGID=100
    volumes:
      - ./app:/app/config
      - ./app/public/images:/app/public/images
      - ./app/public/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
