http:
  routers:
    traefik-dashboard:
      entryPoints:
        - web
        - websecure
      rule: "Host(`traefik.example.com`)"
      service: api@internal
      middlewares:
        - default-ipallowlist
        - default-headers
        - https-redirect
      tls:
        certResolver: selectelv2
#
    traefik-dashboard-admin:
      entryPoints:
        - web
        - websecure
      rule: "Host(`dash.traefik.example.com`)"
      service: noop@internal
      middlewares:
        - default-ipallowlist
        - traefik_plugin_AdminAPI_WebUI
        - default-headers
        - https-redirect
      tls:
        certResolver: selectelv2
#
    dockhand:
      entryPoints:
        - web
        - websecure
      rule: "Host(`dockhand.example.com`)"
      middlewares:
        - default-headers
        - https-redirect
      tls:
        certResolver: selectelv2
      service: dockhand
#
#
  services:
    dockhand:
      loadBalancer:
        servers:
          - url: "http://ip:3000"
        passHostHeader: true

