services:
  crafty:
    container_name: crafty
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: unless-stopped
    ports:
      - "5520-5550:5520-5550/udp" # Hytale
      - "8000:8000" # HTTP
      - "8443:8443" # HTTPS
      - "8123:8123" # DYNMAP
      - "19132:19132/udp" # BEDROCK
      - "25500-25600:25500-25600" # MC SERV PORT RANGE
    environment:
      - TZ=Asia/Yekanerinburg
    volumes:
      - ${DATA_ROOT:-./data}/logs:/crafty/logs
      - ${DATA_ROOT:-./data}/config:/crafty/app/config
      - ${DATA_ROOT:-./data}/import:/crafty/import
      - ${DATA_ROOT:-./data}/backups:/crafty/backups
      - ${DATA_ROOT:-./data}/servers:/crafty/servers
    networks:
      - frontend

networks:
  frontend:
    external: true