services:
  sillytavern:
    container_name: sillytavern
    image: ghcr.io/sillytavern/sillytavern:latest
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=production
      - FORCE_COLOR=1
    volumes:
      - ${DATA_ROOT:-./data}/config:/home/node/app/config
      - ${DATA_ROOT:-./data}/data:/home/node/app/data
      - ${DATA_ROOT:-./data}/plugins:/home/node/app/plugins
      - ${DATA_ROOT:-./data}/extensions:/home/node/app/public/scripts/extensions/third-party
    security_opt:
      - no-new-privileges=true
    networks:
      - frontend
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true