services:
  sillytavern:
    container_name: sillytavern
    image: ghcr.io/sillytavern/sillytavern:latest
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=production
      - FORCE_COLOR=1
    volumes:
      - /home/syllytavern/config:/home/node/app/config
      - /home/syllytavern/data:/home/node/app/data
      - /home/syllytavern/plugins:/home/node/app/plugins
      - /home/syllytavern/extensions:/home/node/app/public/scripts/extensions/third-party
    security_opt:
      - no-new-privileges=true
    networks:
      - frontend
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true