services:
  trilium:
    container_name: trilium
    image: triliumnext/trilium:latest
    restart: unless-stoped
    ports:
      - 8080:8080
    environment:
      TRILIUM_NETWORK_TRUSTEDREVERSEPROXY=172.18.0.0/16
      TRILIUM_DATA_DIR=/home/node/trilium-data
      TZ=UTC
    volumes:
      - ./trilium:/home/node/trilium-data
    networks:
      proxy:
networks:
  proxy:
    external: true