---
services:
  passbolt:
    image: passbolt/passbolt:latest-ce
    container_name: passbolt
    restart: unless-stopped
    ports:
      - 8443:443
      - 8082:80
    environment:
      - APP_FULL_BASE_URL=${APP_FULL_BASE_URL}
      - DATASOURCES_DEFAULT_URL=${DATASOURCES_DEFAULT_URL}
      - DATASOURCES_DEFAULT_DRIVER=Cake\Database\Driver\Postgres
      - DATASOURCES_DEFAULT_ENCODING=utf8
      - EMAIL_TRANSPORT_DEFAULT_HOST=${EMAIL_TRANSPORT_DEFAULT_HOST}
      - EMAIL_TRANSPORT_DEFAULT_PORT=${EMAIL_TRANSPORT_DEFAULT_PORT}
      - EMAIL_TRANSPORT_DEFAULT_USERNAME=${EMAIL_TRANSPORT_DEFAULT_USERNAME}
      - EMAIL_TRANSPORT_DEFAULT_PASSWORD=${EMAIL_TRANSPORT_DEFAULT_PASSWORD}
      - EMAIL_TRANSPORT_DEFAULT_TLS=${EMAIL_TRANSPORT_DEFAULT_TLS}
      - EMAIL_DEFAULT_FROM=${EMAIL_DEFAULT_FROM}
    volumes:
      - /home/passbolt/gpg:/etc/passbolt/gpg
      - /home/passbolt/jwt:/etc/passbolt/jwt
    security_opt:
      - no-new-privileges=true
    env_file:
      - .env
    command: ["/usr/bin/wait-for.sh", "-t", "0", "postgres:5432", "--", "/docker-entrypoint.sh"]
    networks:
      - frontend
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true