services:
  dockge:
    container_name: dockge
    image: louislam/dockge:1
    restart: unless-stopped
    environment:
      - DOCKGE_STACKS_DIR=/volume1/docker
      - DOCKGE_ENABLE_CONSOLE=true
    ports:
      - 5003:5001
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    security_opt:
      - no-new-privileges=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /volume1/docker:/volume1/docker